name: Run BDD Tests (Playwright + Cucumber)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run All Cucumber Tests (UI + API)
        run: npm run test:all:headless

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate ./allure-results -o ./allure-report --clean
        if: always()

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          